version: '3.8'

services:
  mcp-vision:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-vision-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount volume for persistent cache if needed
      - mcp-vision-cache:/app/.cache
    networks:
      - mcp-network

  # Optional: Add nginx reverse proxy for SSL termination and load balancing
  nginx:
    image: nginx:alpine
    container_name: mcp-vision-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-vision
    restart: unless-stopped
    networks:
      - mcp-network
    profiles:
      - with-nginx

volumes:
  mcp-vision-cache:
    driver: local

networks:
  mcp-network:
    driver: bridge